# Generated by Django 3.2.8 on 2021-10-25 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_lessons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lessons',
            new_name='Lesson',
        ),
    ]
