# Generated by Django 3.2.8 on 2022-04-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
