# Generated by Django 3.2.8 on 2022-07-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20220706_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
